name: Mirror cumdaura feeds to gh-pages

on:
  schedule:
    - cron: "*/6 * * * *"
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run mirror.js
        run: node mirror.js

      - name: Commit & push mirror files to gh-pages
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "chore: auto‑update cumdauramirror*.xml"
          add: "cumdauramirror*.xml"
          branch: gh-pages
          push: --set-upstream origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```yaml
name: Mirror cumdaura feeds

on:
  schedule:
    # Runs every 15 minutes; adjust as you like
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run mirror.js
        run: node mirror.js

      - name: Commit & push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "chore: auto‑update cumdauramirror*.xml"
          add: "cumdauramirror*.xml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
